### ISSUE TITLE
Dials step by 10

### ISSUE THREAD

**Issue by K9YK** [mkcmsoftware/FRStack_Stream_Deck#1]
The new dial functionality in v1.3 seems to be fixed at incrementing/decrementing by a value of ten when changing slice volume or AGC-T.  These step values are too large to be useful when making adjustments.  Suggestion would be to provide an additional input box to allow the user to specify the step value added in the REST API call.

**Comment by mkcmsoftware** [comment]
This issue was addressed in version 1.4 release.
